### ISSUE TITLE
Issues with Strings Passed to / Used in Macros

### ISSUE THREAD

**Issue by d5aa962e** [dfgordon/vscode-language-merlin6502#2]
There are two parts to this issue:

a) When passing data to a String Data psuedo op (as in a macro), the variable is flagged with a syntax error:

```
ASZ	mac
	asc	]1    <-- This is flagged as "missing ']')
	hex	00
	<<<

ASZ2	mac
	asc	]1]   <-- This is not flagged, but is invalid syntax,
	hex	00         the ]'s are taken as valid delimiters.
	<<<
```
b) Strings with spaces cannot be passed to a macro:

```
Start
	ASZ	"HelloWorld"    <-- This works.
	ASZ	"Hello World"   <-- The text _World"_ is flagged with a global syntax error. 
```
...and although not explicitly stated in the manual, square brackets are valid delimiters (as they have an "ASCII value greater than an apostrophe"):
```
	ASC	]Hello World]   <-- Interestingly, this produces valid, positive bytes.
```

**Comment by dfgordon** [comment]
The extension accepts all the delimiters, but it isn't accounting for all the precedence rules.  It appears if the first character in the string delimited by `]` is 1-8, then interpretation as a variable takes precedence, regardless of what follows, and regardless of context.

For the space we can have `"hello world"` or `'hello world'` in the macro argument, but not `&hello world&` (or any delimiter other than quotes if there are spaces).  In the ordinary pseudo-op arguments it is more flexible.

I think the parser can be updated to account for these rules fairly soon.

**Comment by dfgordon** [comment]
version 2.0.1 should take care of the issues

**Comment by d5aa962e** [comment]
Works great!  Thanks!
